name: My Panda Flow 2
on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-20.04
    name: my second build
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5.2.0
        with: 
          go-version: 1.23.0

      - name: what is go version in this branch
        run: |
          go version
          ls
          go test -cover

      - name: Checkout private repo remotely
        uses: actions/checkout@v4
        with:
          repository: Lowkh/PandaHiddenRepo
          path: hiddenFolder
          token: ${{ secrets.PANDA_TOKEN }}

      - name: List out hidden things
        run: |
          ls
          cd hiddenFolder
          ls
          cd ..
